# transaction plugin name needs to be known in order to produce correct include paths in c++ builders

AccountLinkTransaction: account_link

AggregateCompleteTransaction: aggregate
AggregateBondedTransaction: aggregate

HashLockTransaction: lock_hash

TransferTransaction: transfer

SecretLockTransaction: lock_secret
SecretProofTransaction: lock_secret

MosaicDefinitionTransaction: mosaic
MosaicSupplyChangeTransaction: mosaic

ModifyMultisigAccountTransaction: multisig

AddressAliasTransaction: namespace
MosaicAliasTransaction: namespace
RegisterNamespaceTransaction: namespace

AddressPropertyTransaction: property
MosaicPropertyTransaction: property
TransactionTypePropertyTransaction: property
